#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_chauffeur_index:
   path: /chauffeur
   controller: App\Controller\ChauffeurController::index


app_chauffeur_new:
   path: /chauffeur/new
   controller: App\Controller\ChauffeurController::new



app_chauffeur_show:
   path: /chauffeur/{id}
   controller: App\Controller\ChauffeurController::show




app_chauffeur_edit:
   path: /{id}/edit
   controller: App\Controller\ChauffeurController::edit


app_chauffeur_delete:
   path: /{id}
   controller: App\Controller\ChauffeurController::delete


app_chauffeur_api:
   path: /{id}/api
   controller: App\Controller\ChauffeurController::ChauffeurApi



app_chauffeur_new_api:
   path: /Chauffeurnew
   controller: App\Controller\ChauffeurController::Chauffeurnew



