# index:
#    path: /
#     controller: App\Controller\DefaultController::index

app_register:
   path: /register
   controller: App\Controller\RegistrationController::register


app_chauffeur_index:
   path: /chauffeur
   controller: App\Controller\ChauffeurController::index


app_chauffeur_new:
   path: /chauffeur/new
   controller: App\Controller\ChauffeurController::new



app_chauffeur_show:
   path: /chauffeur/{id}
   controller: App\Controller\ChauffeurController::show




app_chauffeur_edit:
   path: /{id}/edit
   controller: App\Controller\ChauffeurController::edit


app_chauffeur_delete:
   path: /{id}
   controller: App\Controller\ChauffeurController::delete


app_chauffeur_api:
   path: /{id}/api
   controller: App\Controller\ChauffeurController::ChauffeurApi



app_chauffeur_new_api:
   path: api/Chauffeurnew
   controller: App\Controller\ChauffeurController::Chauffeurnew


app_delete_chauffeur_api:
   path: api/delete_chauffeur_api/{id}
   controller: App\Controller\ChauffeurController::delete_chauffeur_api


app_chauffeur_update_api:
   path: api/Chauffeurupdate/{id}
   controller: App\Controller\ChauffeurController::Chauffeurupdate



